# Generated by Django 2.1.1 on 2018-10-20 02:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Academic_year',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ay', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Curriculum',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=200, null=True, unique=True)),
                ('semister', models.CharField(max_length=20, null=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student_profile.Course')),
            ],
        ),
        migrations.CreateModel(
            name='DaySched',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='EnrollbyStudent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enrollment_key', models.SlugField(null=True, unique=True)),
                ('semister', models.CharField(max_length=20)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('status', models.CharField(max_length=100, null=True)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student_profile.Academic_year')),
                ('course', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='student_profile.Course')),
            ],
        ),
        migrations.CreateModel(
            name='GradeSubmitted',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Instructor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('middle_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('gender', models.CharField(blank=True, max_length=20)),
                ('address', models.CharField(blank=True, max_length=100, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Major',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('description', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(max_length=50, null=True, unique=True)),
                ('first_name', models.CharField(max_length=100)),
                ('middle_name', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=100)),
                ('birth_date', models.DateTimeField(blank=True, null=True)),
                ('address', models.CharField(blank=True, max_length=200, null=True)),
                ('city', models.CharField(blank=True, max_length=200, null=True)),
                ('province', models.CharField(blank=True, max_length=200, null=True)),
                ('place_of_birth', models.CharField(blank=True, max_length=200, null=True)),
                ('mobile_no', models.CharField(blank=True, max_length=40, null=True)),
                ('guardian', models.CharField(blank=True, max_length=200, null=True)),
                ('relationship', models.CharField(blank=True, max_length=200, null=True)),
                ('guardian_address', models.CharField(blank=True, max_length=200, null=True)),
                ('guardian_contact', models.CharField(blank=True, max_length=200, null=True)),
                ('occupation', models.CharField(blank=True, max_length=200, null=True)),
                ('religion', models.CharField(blank=True, max_length=200, null=True)),
                ('zip_code', models.CharField(blank=True, max_length=20, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('primary', models.CharField(blank=True, max_length=200, null=True)),
                ('elementary', models.CharField(blank=True, max_length=200, null=True)),
                ('highschool', models.CharField(blank=True, max_length=200, null=True)),
                ('degree_completed', models.CharField(blank=True, max_length=200, null=True)),
                ('degree_year_attended', models.CharField(blank=True, max_length=8, null=True)),
                ('name_of_school', models.CharField(blank=True, max_length=200, null=True)),
                ('primary_completed', models.CharField(blank=True, max_length=8, null=True)),
                ('elementary_completed', models.CharField(blank=True, max_length=8, null=True)),
                ('highschool_completed', models.CharField(blank=True, max_length=8, null=True)),
                ('civil_status', models.CharField(blank=True, max_length=200, null=True)),
                ('nationality', models.CharField(blank=True, max_length=200, null=True)),
                ('email_add', models.CharField(blank=True, max_length=200, null=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student_profile.Course')),
                ('major', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='student_profile.Major')),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=200, unique=True)),
                ('description', models.CharField(max_length=200)),
                ('unit', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='SubjectsLoaded',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enrolled_by_student', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='student_profile.EnrollbyStudent')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student_profile.Subject')),
            ],
        ),
        migrations.CreateModel(
            name='TimeSched',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='UploadExcel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(null=True, upload_to='xls/')),
            ],
        ),
        migrations.CreateModel(
            name='Year_level',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=6)),
                ('description', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='gradesubmitted',
            name='intructor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student_profile.Instructor'),
        ),
        migrations.AddField(
            model_name='gradesubmitted',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student_profile.Student'),
        ),
        migrations.AddField(
            model_name='gradesubmitted',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student_profile.Subject'),
        ),
        migrations.AddField(
            model_name='enrollbystudent',
            name='major',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='student_profile.Major'),
        ),
        migrations.AddField(
            model_name='enrollbystudent',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student_profile.Student'),
        ),
        migrations.AddField(
            model_name='enrollbystudent',
            name='year_level',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='student_profile.Year_level'),
        ),
        migrations.AddField(
            model_name='curriculum',
            name='major',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='student_profile.Major'),
        ),
        migrations.AddField(
            model_name='curriculum',
            name='subjects',
            field=models.ManyToManyField(related_name='Curriculum_subjects', to='student_profile.Subject'),
        ),
        migrations.AddField(
            model_name='curriculum',
            name='year_level',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='student_profile.Year_level'),
        ),
    ]
