# Generated by Django 2.1.1 on 2018-10-20 02:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student_profile', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subjectsloaded',
            name='day',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='student_profile.DaySched'),
        ),
        migrations.AddField(
            model_name='subjectsloaded',
            name='instructor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='student_profile.Instructor'),
        ),
        migrations.AddField(
            model_name='subjectsloaded',
            name='room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='student_profile.Room'),
        ),
        migrations.AddField(
            model_name='subjectsloaded',
            name='time',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='student_profile.TimeSched'),
        ),
    ]
