# Generated by Django 2.1.1 on 2018-10-20 03:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student_profile', '0002_auto_20181020_1058'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subjectsloaded',
            name='day',
        ),
        migrations.RemoveField(
            model_name='subjectsloaded',
            name='instructor',
        ),
        migrations.RemoveField(
            model_name='subjectsloaded',
            name='room',
        ),
        migrations.RemoveField(
            model_name='subjectsloaded',
            name='time',
        ),
    ]
