# Generated by Django 2.1.1 on 2018-10-20 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_profile', '0003_auto_20181020_1100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='code',
            field=models.CharField(max_length=200),
        ),
    ]
