# Generated by Django 2.1.1 on 2018-10-20 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_profile', '0004_auto_20181020_2211'),
    ]

    operations = [
        migrations.AddField(
            model_name='subjectsloaded',
            name='status',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
