# Generated by Django 2.1.1 on 2018-10-20 23:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student_profile', '0005_subjectsloaded_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='curriculum',
            name='slug',
        ),
    ]
