# Generated by Django 2.1.1 on 2018-10-20 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_profile', '0006_remove_curriculum_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='curriculum',
            name='slug',
            field=models.SlugField(max_length=200, null=True, unique=True),
        ),
    ]
