# Generated by Django 2.1.1 on 2018-10-22 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_profile', '0007_curriculum_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='middle_name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
