# Generated by Django 2.1.1 on 2018-10-23 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_profile', '0010_auto_20181022_1737'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='degree_completed',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
