# Generated by Django 2.1.1 on 2018-10-23 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_profile', '0011_auto_20181022_1809'),
    ]

    operations = [
        migrations.CreateModel(
            name='IDandFullname',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(max_length=50, null=True, unique=True)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
            ],
        ),
    ]
