# Generated by Django 2.1.1 on 2018-10-23 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_profile', '0012_idandfullname'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='ext_name',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
