# Generated by Django 2.1.1 on 2018-10-23 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_profile', '0013_student_ext_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curriculum',
            name='slug',
            field=models.SlugField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='enrollbystudent',
            name='enrollment_key',
            field=models.SlugField(null=True),
        ),
    ]
