# Generated by Django 2.1.1 on 2018-10-23 20:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student_profile', '0014_auto_20181023_2124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrollbystudent',
            name='academic_year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='student_profile.Academic_year'),
        ),
        migrations.AlterField(
            model_name='enrollbystudent',
            name='course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='student_profile.Course'),
        ),
        migrations.AlterField(
            model_name='enrollbystudent',
            name='major',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='student_profile.Major'),
        ),
        migrations.AlterField(
            model_name='enrollbystudent',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='student_profile.Student'),
        ),
        migrations.AlterField(
            model_name='enrollbystudent',
            name='year_level',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='student_profile.Year_level'),
        ),
    ]
