# Generated by Django 2.1.1 on 2019-04-12 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_profile', '0015_auto_20181024_0424'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='enrollbystudent',
            options={'ordering': ['major', 'year_level', 'student']},
        ),
        migrations.AlterModelOptions(
            name='student',
            options={'ordering': ['last_name']},
        ),
        migrations.AddField(
            model_name='academic_year',
            name='status',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
    ]
