# Generated by Django 2.1.1 on 2019-05-21 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_profile', '0016_auto_20190412_1436'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='lrn_num',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
