# Generated by Django 2.1.1 on 2019-06-27 12:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student_profile', '0017_student_lrn_num'),
    ]

    operations = [
        migrations.AddField(
            model_name='subjectsloaded',
            name='grade_status',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='subjectsloaded',
            name='instructor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='student_profile.Instructor'),
        ),
    ]
