# Generated by Django 2.1.1 on 2019-06-27 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_profile', '0018_auto_20190627_2039'),
    ]

    operations = [
        migrations.AddField(
            model_name='subjectsloaded',
            name='grade',
            field=models.IntegerField(null=True),
        ),
    ]
