# Generated by Django 2.1.1 on 2019-07-02 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_profile', '0020_auto_20190702_2010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='academic_year',
            name='status',
            field=models.NullBooleanField(),
        ),
    ]
