# Generated by Django 2.1.1 on 2019-07-03 14:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student_profile', '0021_auto_20190702_2013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='academic_year',
            name='status',
            field=models.NullBooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='enrollbystudent',
            name='academic_year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='enrollbyStudents', to='student_profile.Academic_year'),
        ),
        migrations.AlterField(
            model_name='enrollbystudent',
            name='course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='enrollbyStudents', to='student_profile.Course'),
        ),
        migrations.AlterField(
            model_name='enrollbystudent',
            name='major',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='enrollbyStudents', to='student_profile.Major'),
        ),
        migrations.AlterField(
            model_name='enrollbystudent',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='enrollbyStudents', to='student_profile.Student'),
        ),
        migrations.AlterField(
            model_name='enrollbystudent',
            name='year_level',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='enrollbyStudents', to='student_profile.Year_level'),
        ),
    ]
