# Generated by Django 2.1.1 on 2019-07-04 11:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student_profile', '0022_auto_20190703_2201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to='student_profile.Course'),
        ),
        migrations.AlterField(
            model_name='student',
            name='major',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='students', to='student_profile.Major'),
        ),
        migrations.AlterField(
            model_name='subjectsloaded',
            name='enrolled_by_student',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='enroll_subjects', to='student_profile.EnrollbyStudent'),
        ),
    ]
