# Generated by Django 2.1.1 on 2019-07-05 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_profile', '0023_auto_20190704_1912'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subjectsloaded',
            name='grade',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
