# Generated by Django 2.1.1 on 2020-03-17 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_profile', '0024_auto_20190705_1414'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subjectsloaded',
            name='grade',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='subjectsloaded',
            name='grade_status',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='subjectsloaded',
            name='status',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
