# Generated by Django 2.1.1 on 2020-04-16 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_profile', '0025_auto_20200317_1157'),
    ]

    operations = [
        migrations.CreateModel(
            name='AOSF',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('athletic_fees', models.DecimalField(decimal_places=2, default=0.0, max_digits=20)),
                ('computer_fees', models.DecimalField(decimal_places=2, default=0.0, max_digits=20)),
                ('cultural_fees', models.DecimalField(decimal_places=2, default=0.0, max_digits=20)),
                ('guidance_fees', models.DecimalField(decimal_places=2, default=0.0, max_digits=20)),
                ('handbook_fees', models.DecimalField(decimal_places=2, default=0.0, max_digits=20)),
                ('laboratory_fees', models.DecimalField(decimal_places=2, default=0.0, max_digits=20)),
                ('medical_and_dental_fees', models.DecimalField(decimal_places=2, default=0.0, max_digits=20)),
                ('registration_fees', models.DecimalField(decimal_places=2, default=0.0, max_digits=20)),
                ('school_id_fees', models.DecimalField(decimal_places=2, default=0.0, max_digits=20)),
            ],
        ),
    ]
