# Generated by Django 2.1.1 on 2020-04-16 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_profile', '0026_aosf'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aosf',
            old_name='computer_fees',
            new_name='computer_laboratory_fees',
        ),
        migrations.AddField(
            model_name='aosf',
            name='development_fee',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=20),
        ),
        migrations.AddField(
            model_name='aosf',
            name='entrance_exam',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=20),
        ),
        migrations.AddField(
            model_name='aosf',
            name='internet_fees',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=20),
        ),
    ]
