# Generated by Django 2.1.1 on 2020-04-16 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_profile', '0027_auto_20200416_0941'),
    ]

    operations = [
        migrations.AddField(
            model_name='aosf',
            name='library_fee',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=20),
        ),
    ]
