# Generated by Django 2.1.1 on 2020-04-16 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_profile', '0028_aosf_library_fee'),
    ]

    operations = [
        migrations.AddField(
            model_name='aosf',
            name='tution_fee_ammount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=20),
        ),
    ]
