# Generated by Django 2.1.1 on 2020-05-18 02:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student_profile', '0030_aosf_insurance'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstructorLoadSubject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semister', models.CharField(max_length=20)),
                ('schedule_days', models.CharField(max_length=100)),
                ('is_lab', models.NullBooleanField(default=False)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student_profile.Course')),
                ('intructor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student_profile.Instructor')),
                ('major', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='student_profile.Major')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student_profile.Room')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student_profile.Subject')),
                ('time', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student_profile.TimeSched')),
                ('year_level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student_profile.Year_level')),
            ],
        ),
    ]
