# Generated by Django 2.1.1 on 2020-07-07 06:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student_profile', '0031_instructorloadsubject'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instructorloadsubject',
            name='intructor',
        ),
        migrations.RemoveField(
            model_name='timesched',
            name='time',
        ),
        migrations.AddField(
            model_name='daysched',
            name='number_of_days',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='instructor',
            name='contact',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='instructorloadsubject',
            name='academic_year',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='student_profile.Academic_year'),
        ),
        migrations.AddField(
            model_name='instructorloadsubject',
            name='instructor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='student_profile.Instructor'),
        ),
        migrations.AddField(
            model_name='instructorloadsubject',
            name='section',
            field=models.CharField(default='A', max_length=2),
        ),
        migrations.AddField(
            model_name='student',
            name='brgy',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='street',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='timesched',
            name='days',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='student_profile.DaySched'),
        ),
        migrations.AddField(
            model_name='timesched',
            name='duration_in_hour',
            field=models.FloatField(default=1),
        ),
        migrations.AddField(
            model_name='timesched',
            name='time_start',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='instructorloadsubject',
            name='schedule_days',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='student_profile.DaySched'),
        ),
        migrations.AlterField(
            model_name='student',
            name='address',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
