# Generated by Django 2.1.1 on 2021-03-17 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_profile', '0032_auto_20200707_1420'),
    ]

    operations = [
        migrations.AddField(
            model_name='aosf',
            name='graduation_fee',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=20, null=True),
        ),
    ]
