# Generated by Django 2.1.1 on 2021-05-09 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_profile', '0033_aosf_graduation_fee'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='is_conditional',
            field=models.NullBooleanField(default=False),
        ),
    ]
