# Generated by Django 2.1.1 on 2021-05-09 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_profile', '0034_student_is_conditional'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActiveSem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semister', models.CharField(max_length=20)),
            ],
        ),
    ]
