# Generated by Django 2.1.1 on 2021-05-09 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_profile', '0035_activesem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activesem',
            name='semister',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
