# Generated by Django 2.1.1 on 2021-09-17 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_profile', '0036_auto_20210509_1552'),
    ]

    operations = [
        migrations.AddField(
            model_name='subjectsloaded',
            name='midterm_grade',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
