# Generated by Django 4.1.3 on 2022-11-12 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_profile', '0037_subjectsloaded_midterm_grade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='academic_year',
            name='status',
            field=models.BooleanField(default=True, null=True),
        ),
        migrations.AlterField(
            model_name='instructorloadsubject',
            name='is_lab',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='is_conditional',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
