# Generated by Django 4.2.2 on 2023-06-23 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_profile', '0038_alter_academic_year_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='senior_highschool',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='senior_highschool_completed',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
    ]
