# Generated by Django 4.2.2 on 2023-06-28 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_profile', '0039_student_senior_highschool_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='date_accepted',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
