# Generated by Django 5.1 on 2024-08-21 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_profile', '0041_announcement_studentprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='prerequisite_for',
            field=models.ManyToManyField(related_name='prerequisites', to='student_profile.subject'),
        ),
    ]
