# Generated by Django 5.1 on 2024-09-26 08:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_profile', '0041_announcement_studentprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='prerequisite',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prerequisite_for', to='student_profile.subject'),
        ),
    ]
