# Generated by Django 5.1 on 2024-09-27 02:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_profile', '0042_subject_prerequisite'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='idandfullname',
            name='added_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='added_id_fillname', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='idandfullname',
            name='instructor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='student_profile.instructor'),
        ),
        migrations.AddField(
            model_name='idandfullname',
            name='is_dean',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='idandfullname',
            name='is_student',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='idandfullname',
            name='is_teacher',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='idandfullname',
            name='related_students',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='student_profile.student'),
        ),
        migrations.AddField(
            model_name='idandfullname',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
