# Generated by Django 5.1 on 2024-09-29 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student_profile', '0042_subject_prerequisite_for'),
        ('student_profile', '0043_idandfullname_added_by_idandfullname_instructor_and_more'),
    ]

    operations = [
    ]
