# Generated by Django 5.1 on 2024-10-17 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_profile', '0045_remove_subject_prerequisite_for_student_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='subjectsloaded',
            name='submit_status',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
