# Generated by Django 5.1 on 2024-10-19 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student_profile', '0047_instructor_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instructor',
            name='user',
        ),
    ]
