# Generated by Django 5.1 on 2024-10-24 06:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_profile', '0048_remove_instructor_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='idandfullname',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='student_profile.course'),
        ),
        migrations.AddField(
            model_name='idandfullname',
            name='subjects',
            field=models.ManyToManyField(blank=True, related_name='teachers', to='student_profile.subject'),
        ),
    ]
