# Generated by Django 5.1 on 2024-11-05 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_profile', '0050_instructor_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='idandfullname',
            name='status',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='idandfullname',
            name='subjects',
            field=models.ManyToManyField(blank=True, null=True, related_name='teachers', to='student_profile.subject'),
        ),
    ]
