# Generated by Django 5.1 on 2024-11-10 14:46

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_profile', '0051_idandfullname_status_alter_idandfullname_subjects'),
    ]

    operations = [
        migrations.CreateModel(
            name='GradeSubmissionSchedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submission_date', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student_profile.subject')),
            ],
        ),
    ]
