# Generated by Django 5.1 on 2024-11-10 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student_profile', '0052_gradesubmissionschedule'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GradeSubmissionSchedule',
        ),
    ]
