# Generated by Django 5.1 on 2024-11-10 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_profile', '0053_delete_gradesubmissionschedule'),
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
            ],
        ),
    ]
