# Generated by Django 5.1 on 2024-11-10 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student_profile', '0054_schedule'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Schedule',
        ),
    ]
