# Generated by Django 5.1 on 2024-11-11 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_profile', '0055_delete_schedule'),
    ]

    operations = [
        migrations.CreateModel(
            name='GradeSubmissionSchedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('status', models.CharField(default='pending', max_length=10)),
            ],
        ),
    ]
