# Generated by Django 5.1 on 2024-11-25 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_profile', '0056_gradesubmissionschedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='subjectsloaded',
            name='submitted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
