# Generated by Django 5.1 on 2024-11-25 14:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_profile', '0057_subjectsloaded_submitted_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subjectsloaded',
            old_name='submitted_at',
            new_name='submission_time',
        ),
        migrations.AddField(
            model_name='subjectsloaded',
            name='academic_year',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='student_profile.academic_year'),
        ),
    ]
