# Generated by Django 5.1 on 2024-11-25 14:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_profile', '0058_rename_submitted_at_subjectsloaded_submission_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subjectsloaded',
            name='semester',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='student_profile.activesem'),
        ),
    ]
