# Generated by Django 5.1 on 2024-11-25 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student_profile', '0059_subjectsloaded_semester'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subjectsloaded',
            name='semester',
        ),
    ]
