# Generated by Django 5.1 on 2024-11-26 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_profile', '0061_subjectsloaded_semester'),
    ]

    operations = [
        migrations.AddField(
            model_name='subjectsloaded',
            name='forward_status',
            field=models.BooleanField(default=False),
        ),
    ]
