# Generated by Django 5.1 on 2024-11-26 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student_profile', '0062_subjectsloaded_forward_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subjectsloaded',
            name='forward_status',
        ),
    ]
