# Generated by Django 5.1 on 2024-11-26 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student_profile', '0063_remove_subjectsloaded_forward_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subjectsloaded',
            old_name='semester',
            new_name='semister',
        ),
    ]
