# Generated by Django 5.1 on 2024-11-26 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_profile', '0064_rename_semester_subjectsloaded_semister'),
    ]

    operations = [
        migrations.AddField(
            model_name='activesem',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
