# Generated by Django 5.1 on 2024-11-26 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_profile', '0065_activesem_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activesem',
            name='status',
            field=models.BooleanField(default=True, null=True),
        ),
    ]
