# Generated by Django 5.1 on 2024-11-28 07:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_profile', '0066_alter_activesem_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='gradesubmissionschedule',
            name='academic_year',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='schedules', to='student_profile.academic_year'),
        ),
        migrations.AddField(
            model_name='gradesubmissionschedule',
            name='active_semester',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='schedules', to='student_profile.activesem'),
        ),
    ]
