# Generated by Django 5.1 on 2024-11-28 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_profile', '0067_gradesubmissionschedule_academic_year_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gradesubmissionschedule',
            name='manually_set',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='gradesubmissionschedule',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('pending', 'Pending'), ('closed', 'Closed'), ('off', 'Off')], default='pending', max_length=10),
        ),
    ]
