# Generated by Django 5.1 on 2024-11-28 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student_profile', '0068_gradesubmissionschedule_manually_set_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gradesubmissionschedule',
            name='manually_set',
        ),
        migrations.RemoveField(
            model_name='gradesubmissionschedule',
            name='status',
        ),
    ]
