# Generated by Django 5.1 on 2024-11-28 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_profile', '0069_remove_gradesubmissionschedule_manually_set_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gradesubmissionschedule',
            name='status',
            field=models.CharField(default='pending', max_length=10),
        ),
    ]
