# Generated by Django 5.1 on 2024-11-28 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student_profile', '0070_gradesubmissionschedule_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gradesubmissionschedule',
            old_name='active_semester',
            new_name='active_semister',
        ),
    ]
