# Generated by Django 5.1 on 2024-11-29 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student_profile', '0072_alter_student_birth_date_alter_student_brgy_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subjectsloaded',
            name='academic_year',
        ),
        migrations.RemoveField(
            model_name='subjectsloaded',
            name='semister',
        ),
        migrations.RemoveField(
            model_name='subjectsloaded',
            name='submission_time',
        ),
    ]
