# Generated by Django 5.1 on 2024-11-29 12:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_profile', '0073_remove_subjectsloaded_academic_year_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subjectsloaded',
            name='academic_year',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='student_profile.academic_year'),
        ),
        migrations.AddField(
            model_name='subjectsloaded',
            name='semister',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='student_profile.activesem'),
        ),
        migrations.AddField(
            model_name='subjectsloaded',
            name='submission_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
