# Generated by Django 5.1 on 2024-11-29 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student_profile', '0074_subjectsloaded_academic_year_subjectsloaded_semister_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activesem',
            name='status',
        ),
    ]
